services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1